### ISSUE TITLE
panic: runtime error: index out of range - ubuntu 16.04 + vuls history

### ISSUE THREAD

**Issue by novakin** [future-architect/vuls#180]
Me again,

`vuls tui` is broken for me on Ubuntu 16.04

> username@ubuntu:~$ vuls tui
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> panic(0xc72320, 0xc82000e070)
>         /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
> github.com/future-architect/vuls/report.selectScanHistory(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /home/username/.go/src/github.com/future-architect/vuls/report/tui.go:82 +0x273
> github.com/future-architect/vuls/report.RunTui(0x0, 0x0, 0x0)
>         /home/username/.go/src/github.com/future-architect/vuls/report/tui.go:45 +0x79
> github.com/future-architect/vuls/commands.(*TuiCmd).Execute(0xc8202e4810, 0x7f9c919ee100, 0xc82000e270, 0xc8202a1800, 0x0, 0x0, 0x0, 0x419278)
>         /home/username/.go/src/github.com/future-architect/vuls/commands/tui.go:104 +0x47d
> github.com/google/subcommands.(*Commander).Execute(0xc82005c070, 0x7f9c919ee100, 0xc82000e270, 0x0, 0x0, 0x0, 0x7f9c919ee100)
>         /home/username/.go/src/github.com/google/subcommands/subcommands.go:142 +0x517
> github.com/google/subcommands.Execute(0x7f9c919ee100, 0xc82000e270, 0x0, 0x0, 0x0, 0xc8202e2df0)
>         /home/username/.go/src/github.com/google/subcommands/subcommands.go:372 +0x55
> main.main()
>         /home/username/.go/src/github.com/future-architect/vuls/main.go:55 +0x715

Should vuls record results even if the scan didnt return any unsecured package ? 
Should vuls record history if a scan returned no unsecured package ?

vuls history returns nothing even if i ran multiple scans

**Comment by novakin** [comment]
I'm really sorry but it was my fault.  go-cve-dictionary server was misconfigured and not running

Still can you tell me if Vuls create results file and log history only if unsecured packages where found ?

**Comment by novakin** [comment]
Running vuls scan -report-json fixes the problem :-)

Sorry for the pointless issue, :/
