### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gy741** [future-architect/vuls#944]
# What did you do? (required. The issue will be **closed** when not provided.)

Hello.

I found invalid memory address or nil pointer dereference bug in vuls.

Please confirm.

Thanks.

reproduce code:
```
package scan

import (
        "testing"
)

func TestFuzzCrashers(t *testing.T) {

        var crashers = []string{
                ",00,,,",
        }
        o := &debian{}
        for _, f := range crashers {
                o.parseInstalledPackages(string(f))
        }
}
```

Crash log:
```
--- FAIL: TestFuzzCrashers (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6f2ef6]

goroutine 37 [running]:
testing.tRunner.func1.1(0xf5ea20, 0x1c174e0)
        /usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc00010aea0)
        /usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0xf5ea20, 0x1c174e0)
        /usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/sirupsen/logrus.(*Entry).Logf(0x0, 0x5, 0x10a4b59, 0x23, 0xc0000618c0, 0x2, 0x2)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:313 +0x26
github.com/sirupsen/logrus.(*Entry).Debugf(...)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:323
github.com/future-architect/vuls/scan.(*debian).parseInstalledPackages(0xc0000f7af8, 0x107f42f, 0x6, 0x4, 0xd0, 0x4, 0x0)
        /root/go/src/github.com/future-architect/vuls/scan/debian.go:404 +0x390
github.com/future-architect/vuls/scan.TestFuzzCrashers(0xc00010aea0)
        /root/go/src/github.com/future-architect/vuls/scan/debian_fuzz_test.go:14 +0xbe
testing.tRunner(0xc00010aea0, 0x110d1b0)
        /usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1043 +0x357
exit status 2
FAIL    github.com/future-architect/vuls/scan   0.053s
```

# What did you expect to happen?

# What happened instead?

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):

* Go environment (`go env`):

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by gy741** [comment]
I think there is no null check for the "packageStatus" variable.

What do you think?


```
	for _, line := range lines {
		if trimmed := strings.TrimSpace(line); len(trimmed) != 0 {
			name, status, version, srcName, srcVersion, err := o.parseScannedPackagesLine(trimmed)
			if err != nil || len(status) < 2 {
				return nil, nil, xerrors.Errorf(
					"Debian: Failed to parse package line: %s", line)
			}


			packageStatus := status[1]
			// Package status:
			//     n = Not-installed
			//     c = Config-files
			//     H = Half-installed
			//     U = Unpacked
			//     F = Half-configured
			//     W = Triggers-awaiting
			//     t = Triggers-pending
			//     i = Installed
			if packageStatus != 'i' {
				o.log.Debugf("%s package status is '%c', ignoring", name, packageStatus)
				continue
			}
			installed[name] = models.Package{
				Name:    name,
				Version: version,
			}
```

**Comment by kotakanbe** [comment]
`status` is a string type and check the length of status here `len(status) < 2`.
so status[1] will never be nil.
